# Site settings
title: noise
email: shaunalynn@powderhouse.org
description: > # this means to ignore newlines until "baseurl:"
  A scrapbook for shduff's Noise & the Novice work at Powderhouse Studios
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: shduff
github_username:  shduff

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/journal/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


